In [1]:
from sklearn.datasets import load_diabetes
from sklearn.linear_model import LinearRegression,Ridge,Lasso,ElasticNet
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [23]:
import pandas as pd
df=pd.read_csv("train.csv")[['Age','Pclass','SibSp','Parch','Survived']]

In [33]:
df=df.dropna()

In [34]:
X=df.iloc[:,0:4]
y=df.iloc[:,-1]

In [35]:
X.head()

    Age  Pclass  SibSp  Parch
0  22.0       3      1      0
1  38.0       1      1      0
2  26.0       3      0      0
3  35.0       1      1      0
4  35.0       3      0      0

In [36]:
X.isnull().sum()

Age       0
Pclass    0
SibSp     0
Parch     0
dtype: int64

In [37]:
X.dropna()

      Age  Pclass  SibSp  Parch
0    22.0       3      1      0
1    38.0       1      1      0
2    26.0       3      0      0
3    35.0       1      1      0
4    35.0       3      0      0
..    ...     ...    ...    ...
885  39.0       3      0      5
886  27.0       2      0      0
887  19.0       1      0      0
889  26.0       1      0      0
890  32.0       3      0      0

[714 rows x 4 columns]

In [38]:
X.isnull().sum()

Age       0
Pclass    0
SibSp     0
Parch     0
dtype: int64

In [39]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [40]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [41]:
# Linear Regression
reg = LinearRegression()
reg.fit(X_train,y_train)
y_pred = reg.predict(X_test)
r2_score(y_test,y_pred)

0.18151628348860605

In [43]:
reg = Ridge(alpha=0.01)
reg.fit(X_train,y_train)
y_pred = reg.predict(X_test)
r2_score(y_test,y_pred)

0.1815148842916149

In [49]:
reg = ElasticNet(alpha=0.00005,l1_ratio=0.0004)
reg.fit(X_train,y_train)
y_pred = reg.predict(X_test)
r2_score(y_test,y_pred)

0.18151226570407597